# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mismatches <- function(hh, y, m, twoSide = TRUE) {
    .Call(`_ProbMatch_mismatches`, hh, y, m, twoSide)
}

matchlk <- function(hh, y, Y, n, m, lmt) {
    .Call(`_ProbMatch_matchlk`, hh, y, Y, n, m, lmt)
}

donorlk <- function(x, X, y, Y, nx, ny, m, lmt, avail, N) {
    .Call(`_ProbMatch_donorlk`, x, X, y, Y, nx, ny, m, lmt, avail, N)
}

