# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mismatches <- function(hh, y, m, twoSides = TRUE) {
    .Call(`_ProbMatch_mismatches`, hh, y, m, twoSides)
}

partmm <- function(hh, y, m) {
    .Call(`_ProbMatch_partmm`, hh, y, m)
}

matchlk <- function(hh, y, Y, n, m, lmt, twoSides = TRUE) {
    .Call(`_ProbMatch_matchlk`, hh, y, Y, n, m, lmt, twoSides)
}

donorlk <- function(x, X, y, Y, nx, ny, m, lmt, avail, N, twoSides = TRUE) {
    .Call(`_ProbMatch_donorlk`, x, X, y, Y, nx, ny, m, lmt, avail, N, twoSides)
}

mismatchesOpt <- function(hh, y, m, twoSides = TRUE) {
    .Call(`_ProbMatch_mismatchesOpt`, hh, y, m, twoSides)
}

partmmOpt <- function(hh, y, m) {
    .Call(`_ProbMatch_partmmOpt`, hh, y, m)
}

matchlkOpt <- function(hh, y, Y, n, m, lmt, twoSides = TRUE) {
    .Call(`_ProbMatch_matchlkOpt`, hh, y, Y, n, m, lmt, twoSides)
}

donorlkOpt <- function(x, X, y, Y, nx, ny, m, lmt, avail, N, twoSides = TRUE) {
    .Call(`_ProbMatch_donorlkOpt`, x, X, y, Y, nx, ny, m, lmt, avail, N, twoSides)
}

